# Generated by Django 3.2.7 on 2021-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtOnly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
