# Generated by Django 4.0 on 2021-12-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtOnly', '0002_demo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo2',
            name='id',
        ),
        migrations.AlterField(
            model_name='demo2',
            name='name',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
