# Generated by Django 3.2.9 on 2022-01-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('branch', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
