# Generated by Django 4.0 on 2022-01-06 10:27

from django.db import migrations, models
import modellll.models


class Migration(migrations.Migration):

    dependencies = [
        ('modellll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modellll.home',),
        ),
        migrations.AddField(
            model_name='home',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[modellll.models.age_check]),
        ),
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
