# Generated by Django 3.2.7 on 2021-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField(max_length=6)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('school_id', models.IntegerField(max_length=11)),
                ('stage', models.IntegerField(max_length=11)),
                ('section', models.CharField(max_length=2)),
                ('is_active', models.SmallIntegerField(max_length=6)),
                ('join_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
