# Generated by Django 3.2.7 on 2021-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.IntegerField(),
        ),
    ]
