# Generated by Django 3.2.7 on 2021-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20211223_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
