# Generated by Django 3.2.7 on 2021-12-23 07:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_parent', models.ManyToManyField(to='modelapp.Student')),
            ],
        ),
    ]
