# Generated by Django 3.2.7 on 2021-12-23 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 13, 5, 48, 760730)),
        ),
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 13, 5, 48, 759732)),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.SmallIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='level_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.SmallIntegerField(default=False),
        ),
    ]
