# Generated by Django 3.2.7 on 2021-12-23 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_auto_20211223_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('classroom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('room_type', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(max_length=12)),
                ('teacher_full_name', models.CharField(max_length=75)),
                ('gender', models.SmallIntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 14, 27, 50, 855007)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 14, 27, 50, 853965)),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('team', models.IntegerField()),
                ('carry_mark', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('class_student', models.ManyToManyField(to='modelapp.Student')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.classroom')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.teacher')),
            ],
        ),
    ]
