# Generated by Django 3.2.7 on 2021-12-23 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0009_auto_20211223_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 14, 37, 32, 102156)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 14, 37, 32, 101119)),
        ),
        migrations.CreateModel(
            name='DeepFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelapp.fake')),
            ],
        ),
    ]
