# Generated by Django 4.0 on 2022-01-06 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0012_alter_parent_created_at_alter_school_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 15, 57, 33, 384724)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 15, 57, 33, 383725)),
        ),
    ]
